name: Build

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 1.8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install gomobile
        run: go install golang.org/x/mobile/cmd/gomobile@latest

      - name: Build android arr
        run: go generate
