name: Build

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Setup Android SDK
        run: |
          curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip sdk-tools.zip -d $HOME/android-sdk
          echo "y" | $HOME/android-sdk/tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "build-tools;30.0.3"
          export PATH=$PATH:$HOME/android-sdk/platform-tools

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install gomobile
        run: go install golang.org/x/mobile/cmd/gomobile@latest

      - name: Build android aar
        run: go generate
